services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch-node1
    environment:
      - discovery.type=zen-disco
      - cluster.name=my-cluster
      - node.name=node1
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticsearch-net

  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch-node2
    environment:
      - discovery.type=zen-disco
      - cluster.name=my-cluster
      - node.name=node2
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    ports:
      - "9201:9200"
      - "9301:9300"
    networks:
      - elasticsearch-net

networks:
  elasticsearch-net:
    driver: bridge
