services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0-slim
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS="-Xms16g -Xmx16g" 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
volumes:
  es_data:
    driver: local
